[font]
size = 12
normal = { family = "JetBrains Mono", style = "Light" }
bold = { family = "JetBrains Mono", style = "SemiBold" }
italic = { family = "JetBrains Mono", style = "LightItalic" }
bold_italic = { family = "JetBrains Mono", style = "Italic" }
