[font]
size = 9
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Light" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Light" }