[font]
size = 12
bold = { family = "FiraCode Nerd Font Mono", style = "SemiBold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Light" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Light" }
