module.exports = {
  config: {
    fontSize: 12,
    fontFamily: 'JetBrains Mono, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    cursorColor: '#fff1f3',
    cursorShape: 'BEAM',
    foregroundColor: '#fff1f3',
    backgroundColor: '#2D2A2E',
    borderColor: '#ffffff',
    cursorAccentColor: '#000000',
    selectionColor: '#72696a',
    colors: {
      black: '#2c2525',
      red: '#fd6883',
      green: '#adda78',
      yellow: '#f9cc6c',
      blue: '#f38d70',
      magenta: '#a8a9eb',
      cyan: '#85dacc',
      white: '#fff1f3',
      lightBlack: '#72696a',
      lightRed: '#fd6883',
      lightGreen: '#adda78',
      lightYellow: '#f9cc6c',
      lightBlue: '#f38d70',
      lightMagenta: '#a8a9eb',
      lightCyan: '#85dacc',
      lightWhite: '#fff1f3',
    },
  },
  plugins: [],
  keymaps: {
  },
};